# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4616c395a5038dd374058e2cd60ed6e9448e6381d021b370129b6da888843d48092a40bdc652895a35f74bf0c11d866f61d4dcee41edc800d26635a1ca504471

test:
  secret_key_base: 6771bcaa091829789e46d3510ce7582f789813b1801cd2d33aa41bf74b9da251b2ebfc6b9c917d1f51d6456cd2c2c8b216a177587b5ed519c384520c0cee484a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
